[build]
publish = "public"

[[redirects]]
from = "/"
to = "https://zealdocs.org"
status = 302

[[redirects]]
from = "/v1/docsets"
to = "/docsets.json"
status = 200

[[redirects]]
from = "/v1/releases"
to = "/releases.json"
status = 200
