name: Docset Sync

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync-dash:
    name: Sync Dash Docsets
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Dash Repositories
        run: |
          git clone https://github.com/Kapeli/feeds.git build/feeds
          git clone https://github.com/Kapeli/Dash-X-Platform-Resources.git build/resources

      - name: Execute
        run: |
          sudo apt-get -y -qq --no-install-recommends install python3-png
          ./process_dash_feeds.py \
            --manifest=docsets.json \
            --blacklist=blacklist.json \
            --resource-dir=build/resources \
            build/feeds \
            public/docsets.json

      - name: Deploy to Vercel
        run: |
          npm install --global vercel pnpm
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
